### ISSUE TITLE
Declaring channels for the packages in the environment

### ISSUE THREAD

**Issue by pablocarb** [brsynth/rptools#33]
Hello,
It will be better to declare the channels for each specific package in the environment yaml file to avoid dependencies issues.

```
name: rptools
dependencies:
  - python <=3.11
  - conda-forge::brs_utils # rpcompletion, rpfba, Args
  - cobra >=0.26.3 # rpfba, rpextractsink, rplibs
  - timeout-decorator # rpextractsink
  - rdkit # rpextractsink, rplibs
  - python-libsbml # rplibs, rpfba
  - numpy # rplibs, rpfba, rpscore, rpthermo
  - pandas # rplibs, rpthermo
  - scipy # rpthermo
  - equilibrator-api # rpthermo
  - equilibrator-cache >=0.5.4 # rpthermo
  - colored # rplibs
  - networkx >=2.5 # rplibs
  - filetype  # rplibs (conda-forge)
  - rr_cache >=3.1.1 # rpcompletion
  - rxn_rebuild # rpcompletion
  - chemlite # rpcompletion ,rpfba, rpthermo
  - h5py # rpscore
  - xgboost # rpscore
  - bs4 # rpviz
  ```

**Comment by tduigou** [comment]
Hello @pablocarb, thanks for the post

All the tools are available through the same and unique conda package `rptools`, which is the reason why we have this conda env file listing "everything". Splitting this into multiple pieces is indeed something we are considering, because of the amount of dependencies. However, splitting code into pieces may probably ask from us more work, because we'll need to take care of the dependencies between the rptools tools (ie updating `rplibs` will imply updating other pakcages, etc).

**Comment by tduigou** [comment]
#feature, to keep in mind for an eventual futur reorganization of « sub-rptools »
